# Generated by Django 2.1 on 2018-09-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='path',
            field=models.CharField(default='/home/alpha-service/backtest-server/media/root/alpha_test/output/test', max_length=100),
            preserve_default=False,
        ),
    ]
