# Generated by Django 2.1 on 2018-09-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_filerecord_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filerecord',
            name='url',
        ),
    ]
