# Generated by Django 2.1 on 2018-08-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='filename',
            field=models.CharField(max_length=100, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='回测名'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='报告号'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(verbose_name='状态'),
        ),
    ]
