# Generated by Django 2.1 on 2018-08-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20180828_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='fileurl',
            field=models.URLField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
