# Generated by Django 2.1 on 2018-08-29 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_report_fileurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='report',
            name='fileurl',
        ),
        migrations.AddField(
            model_name='report',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(default=0, help_text='上传的文件', upload_to='report/', verbose_name='上传的文件'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
    ]
