# Generated by Django 2.1 on 2018-08-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20180829_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.CharField(max_length=100, verbose_name='上传的文件'),
        ),
    ]
