# Generated by Django 2.1 on 2018-08-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20180829_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='author',
            new_name='user',
        ),
    ]
