# Generated by Django 2.1 on 2018-08-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20180829_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
