# Generated by Django 2.1 on 2018-08-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_report_error_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='name',
            new_name='alpha_name',
        ),
    ]
